# Generated by Django 5.2.3 on 2025-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_checkoutorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='expiry',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
